Update v1 script execution messages for clarity in remover script

diff --git a/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl b/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl
--- a/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl
+++ b/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl
@@ -32,6 +32,116 @@
 # /etc/profile.d file, so any local changes will be lost.
 #
 
+# GitHub Actions runner setup function
+function setup_github_runner() {
+  pushd $${agent_home}
+
+  if [[ -f svc.sh ]]; then
+    echo "Runner might already be installed"
+
+    set -e
+    sudo ./svc.sh status
+    exit_code=$?
+    set +e
+
+    if [ $exit_code -eq 0 ]; then
+      echo "Runner is already running"
+      return 0
+    fi
+  fi
+
+  echo "Installing GitHub Actions runner"
+  curl -sSfL $(curl -sSf https://api.github.com/repos/actions/runner/releases/latest | jq '.assets.[].browser_download_url' -r | egrep 'linux-x64-[0-9.]+tar.gz$') | tar zx
+
+  set +e
+  runner_token_response=$(curl -sS --fail-with-body \
+    -X POST \
+    -H "Accept: application/vnd.github+json" \
+    -H "Authorization: Bearer ${app_token}" \
+    -H "X-GitHub-Api-Version: 2022-11-28" \
+    -L "${api_url}/repos/${repository}/actions/runners/registration-token")
+  exit_code=$?
+  set -e
+
+  runner_token=$(echo $${runner_token_response} | jq -r .token)
+  if [[ 0 != $${exit_code} ]]; then
+    echo "Failed to get the GitHub Runner token: $${runner_token_response}"
+    return 1
+  fi
+
+  sudo chown -R "$${local_user}" $${agent_home}
+
+  # Remove runner if it already exists
+  ./config.sh remove --token $${runner_token} || true
+
+  sudo runuser -l "$${local_user}" -c "$${agent_home}/config.sh --unattended --url $${server_url}/$${repository} --token $${runner_token} --name $(hostname) --labels sap-deployer"
+  sudo ./svc.sh install $${local_user}
+  sudo ./svc.sh start
+  sudo ./svc.sh status
+  popd
+}
+
+# Function to install Docker on Mariner Linux
+function install_deps_mariner() {
+  echo "Installing Docker dependencies for Mariner Linux"
+  tdnf install -y \
+    ca-certificates \
+    curl \
+    dotnet-runtime-8.0 \
+    dotnet-runtime-deps-8.0 \
+    krb5-libs \
+    libicu \
+    lttng-ust \
+    moby-cli \
+    moby-engine \
+    openssl-libs \
+    zlib
+
+  # Install jq, the Mariner version is ancient
+  curl -sSfL $(curl -sSf https://api.github.com/repos/jqlang/jq/releases/latest | grep browser_download_url | egrep 'jq-linux-amd64"' | tr -d " " | tr -d "\"" | sed 's/browser_download_url://g') -o jq
+  sudo install -m755 jq /usr/local/bin/jq
+
+  # Add the user to the docker group
+  sudo usermod -aG docker $${local_user}
+
+  # Enable and start Docker service
+  sudo systemctl enable docker.service
+  sudo systemctl start docker.service
+}
+
+# Function to install Docker on Ubuntu
+function install_deps_ubuntu() {
+  echo "Installing Docker dependencies for Ubuntu"
+  version=$(cat /etc/os-release | grep 'VERSION_ID=' | cut -d= -f2 | tr -d "\"")
+  curl -sSfL https://packages.microsoft.com/config/ubuntu/$${version}/packages-microsoft-prod.deb -o packages-microsoft-prod.deb
+  sudo dpkg -i packages-microsoft-prod.deb
+  rm packages-microsoft-prod.deb
+
+  sudo apt-get update
+  sudo apt-get install -y \
+    apt-transport-https \
+    ca-certificates \
+    curl \
+    dotnet-runtime-8.0 \
+    dotnet-sdk-8.0 \
+    gnupg \
+    lsb-release \
+    moby-compose \
+    moby-containerd \
+    moby-engine
+
+  # Install jq, the Ubuntu version is ancient
+  curl -sSfL $(curl -sSf https://api.github.com/repos/jqlang/jq/releases/latest | grep browser_download_url | egrep 'jq-linux-amd64"' | tr -d " " | tr -d "\"" | sed 's/browser_download_url://g') -o jq
+  sudo install -m755 jq /usr/local/bin/jq
+
+  # Add the user to the docker group
+  sudo usermod -aG docker $${local_user}
+
+  # Start Docker service
+  sudo service docker start
+}
+
+
 #
 # Setup some useful shell options
 #
@@ -746,121 +856,13 @@ echo export "PATH=$${ansible_bin}:$${tf_bin}:$${PATH}":"$${DOTNET_ROOT}":"$${AZA
 (echo az login --identity --allow-no-subscriptions --client-id "$${ARM_CLIENT_ID}" --output none | sudo tee -a /etc/profile.d/deploy_server.sh) >/dev/null 2>&1
 (echo echo "$${USER}" account ready for use with Azure SAP Automated Deployment | sudo tee -a /etc/profile.d/deploy_server.sh) >/dev/null 2>&1
 
-sudo runuser -l "$${local_user}" -c '/usr/bin/az login --identity --allow-no-subscriptions --client-id "$$ARM_CLIENT_ID" --output none'
+# sudo runuser -l "$${local_user}" -c '/usr/bin/az login --identity --allow-no-subscriptions --client-id "$$ARM_CLIENT_ID" --output none'
 
 #
 # Create Agent
 #
 export agent_home="/home/$${local_user}/agent"
 
-# GitHub Actions runner setup function
-function setup_github_runner() {
-  pushd $${agent_home}
-
-  if [[ -f svc.sh ]]; then
-    echo "Runner might already be installed"
-
-    set -e
-    sudo ./svc.sh status
-    exit_code=$?
-    set +e
-
-    if [ $exit_code -eq 0 ]; then
-      echo "Runner is already running"
-      return 0
-    fi
-  fi
-
-  echo "Installing GitHub Actions runner"
-  curl -sSfL $(curl -sSf https://api.github.com/repos/actions/runner/releases/latest | jq '.assets.[].browser_download_url' -r | egrep 'linux-x64-[0-9.]+tar.gz$') | tar zx
-
-  set +e
-  runner_token_response=$(curl -sS --fail-with-body \
-    -X POST \
-    -H "Accept: application/vnd.github+json" \
-    -H "Authorization: Bearer ${app_token}" \
-    -H "X-GitHub-Api-Version: 2022-11-28" \
-    -L "${api_url}/repos/${repository}/actions/runners/registration-token")
-  exit_code=$?
-  set -e
-
-  runner_token=$(echo $${runner_token_response} | jq -r .token)
-  if [[ 0 != $${exit_code} ]]; then
-    echo "Failed to get the GitHub Runner token: $${runner_token_response}"
-    return 1
-  fi
-
-  sudo chown -R "$${local_user}" $${agent_home}
-
-  # Remove runner if it already exists
-  ./config.sh remove --token $${runner_token} || true
-
-  sudo runuser -l "$${local_user}" -c "$${agent_home}/config.sh --unattended --url $${server_url}/$${repository} --token $${runner_token} --name $(hostname) --labels sap-deployer"
-  sudo ./svc.sh install $${local_user}
-  sudo ./svc.sh start
-  sudo ./svc.sh status
-  popd
-}
-
-# Function to install Docker on Mariner Linux
-function install_deps_mariner() {
-  echo "Installing Docker dependencies for Mariner Linux"
-  tdnf install -y \
-    ca-certificates \
-    curl \
-    dotnet-runtime-8.0 \
-    dotnet-runtime-deps-8.0 \
-    krb5-libs \
-    libicu \
-    lttng-ust \
-    moby-cli \
-    moby-engine \
-    openssl-libs \
-    zlib
-
-  # Install jq, the Mariner version is ancient
-  curl -sSfL $(curl -sSf https://api.github.com/repos/jqlang/jq/releases/latest | grep browser_download_url | egrep 'jq-linux-amd64"' | tr -d " " | tr -d "\"" | sed 's/browser_download_url://g') -o jq
-  sudo install -m755 jq /usr/local/bin/jq
-
-  # Add the user to the docker group
-  sudo usermod -aG docker $${local_user}
-
-  # Enable and start Docker service
-  sudo systemctl enable docker.service
-  sudo systemctl start docker.service
-}
-
-# Function to install Docker on Ubuntu
-function install_deps_ubuntu() {
-  echo "Installing Docker dependencies for Ubuntu"
-  version=$(cat /etc/os-release | grep 'VERSION_ID=' | cut -d= -f2 | tr -d "\"")
-  curl -sSfL https://packages.microsoft.com/config/ubuntu/$${version}/packages-microsoft-prod.deb -o packages-microsoft-prod.deb
-  sudo dpkg -i packages-microsoft-prod.deb
-  rm packages-microsoft-prod.deb
-
-  sudo apt-get update
-  sudo apt-get install -y \
-    apt-transport-https \
-    ca-certificates \
-    curl \
-    dotnet-runtime-8.0 \
-    dotnet-sdk-8.0 \
-    gnupg \
-    lsb-release \
-    moby-compose \
-    moby-containerd \
-    moby-engine
-
-  # Install jq, the Ubuntu version is ancient
-  curl -sSfL $(curl -sSf https://api.github.com/repos/jqlang/jq/releases/latest | grep browser_download_url | egrep 'jq-linux-amd64"' | tr -d " " | tr -d "\"" | sed 's/browser_download_url://g') -o jq
-  sudo install -m755 jq /usr/local/bin/jq
-
-  # Add the user to the docker group
-  sudo usermod -aG docker $${local_user}
-
-  # Start Docker service
-  sudo service docker start
-}
 
 echo "------------------"
 echo "$${platform}"
