Refactor Terraform pipeline parameters for clarity and update variable names

diff --git a/deploy/pipelines/10-remover-terraform.yaml b/deploy/pipelines/10-remover-terraform.yaml
--- a/deploy/pipelines/10-remover-terraform.yaml
+++ b/deploy/pipelines/10-remover-terraform.yaml
@@ -26,19 +26,19 @@ parameters:
     default:                           true
 
   - name:                              workload_zone
-    displayName:                       "SAP workload zone configuration name, use this format: ENV-LOCA-VNET-INFRASTRUCTURE"
+    displayName:                       "Workload zone configuration name, use the following syntax: ENV-LOCA-VNET-INFRASTRUCTURE"
     type:                              string
     default:                           DEV-WEEU-SAP01-INFRASTRUCTURE
 
-  - name:                              workload_environment
-    displayName:                       Environment (DEV, QUA, PRD)
+  - name:                              workload_zone_name
+    displayName:                       "Workload zone configuration name, use the following syntax: ENV-LOCA-VNET"
     type:                              string
-    default:                           DEV
+    default:                           DEV-WEEU-SAP01
 
-  - name:                              deployer_environment
-    displayName:                       Environment (MGMT)
+  - name:                              control_plane_name
+    displayName:                       "Control plane name, use the following syntax: ENV-LOCA-VNET"
     type:                              string
-    default:                           MMGMT
+    default:                           CPLN-NOEU-DEP01
 
   - name:                              use_deployer
     displayName:                       Run removal on self hosted agent
@@ -74,6 +74,43 @@ stages:
         steps:
           - template: templates\download.yaml
           - task:                      PostBuildCleanup@4
+          - bash: |
+              #!/bin/bash
+              # Exit immediately if a command exits with a non-zero status.
+              set -e
+              if ["${WL_ARM_SUBSCRIPTION_ID:0:2}" == '$(']; then
+                echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;isOutput=true]$WL_ARM_SUBSCRIPTION_ID"
+              else
+                echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;isOutput=true]"
+              fi
+              if ["${WL_ARM_CLIENT_ID:0:2}" == '$(']; then
+                echo "##vso[task.setvariable variable=ARM_CLIENT_ID;isOutput=true]$WL_ARM_CLIENT_ID"
+              else
+                echo "##vso[task.setvariable variable=ARM_CLIENT_ID;isOutput=true]"
+              fi
+              if ["${WL_ARM_CLIENT_SECRET:0:2}" == '$(']; then
+                echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;isOutput=true]$WL_ARM_CLIENT_SECRET"
+              else
+                echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;isOutput=true]"
+              fi
+              if ["${WL_ARM_TENANT_ID:0:2}" == '$(']; then
+                echo "##vso[task.setvariable variable=ARM_TENANT_ID;isOutput=true]$WL_ARM_TENANT_ID"
+              else
+                echo "##vso[task.setvariable variable=ARM_TENANT_ID;isOutput=true]"
+              fi
+              if ["${WL_ARM_OBJECT_ID:0:2}" == '$(']; then
+                echo "##vso[task.setvariable variable=ARM_OBJECT_ID;isOutput=true]$WL_ARM_OBJECT_ID"
+              else
+                echo "##vso[task.setvariable variable=ARM_OBJECT_ID;isOutput=true]"
+              fi
+            env:
+              WL_ARM_SUBSCRIPTION_ID:  $(ARM_SUBSCRIPTION_ID)
+              WL_ARM_CLIENT_ID:        $(ARM_CLIENT_ID),
+              WL_ARM_CLIENT_SECRET:    $(ARM_CLIENT_SECRET)
+              WL_ARM_TENANT_ID:        $(ARM_TENANT_ID)
+              WL_ARM_OBJECT_ID:        $(ARM_OBJECT_ID)
+            name:                      ParameterValidation
+            displayName:               Parameter Validation
           - task:                      Bash@3
             inputs:
               targetType:              'filePath'
@@ -83,15 +120,18 @@ stages:
 
             displayName:               "Remove SAP system"
             env:
-              SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
-              WL_ARM_SUBSCRIPTION_ID:  $(ARM_SUBSCRIPTION_ID)
-              WL_ARM_CLIENT_ID:        $(ARM_CLIENT_ID)
-              WL_ARM_CLIENT_SECRET:    $(ARM_CLIENT_SECRET)
-              WL_ARM_TENANT_ID:        $(ARM_TENANT_ID)
-              AZURE_DEVOPS_EXT_PAT:    $(System.AccessToken)
-              SAP_AUTOMATION_REPO_PATH: ${{ parameters.sap_automation_repo_path }}
-              CONFIG_REPO_PATH:        ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
-              USE_MSI:                 $(Use_MSI)
+              APPLICATION_CONFIGURATION_ID: $(APPLICATION_CONFIGURATION_ID)
+              ARM_CLIENT_ID:                $(ParameterValidation.ARM_CLIENT_ID)
+              ARM_CLIENT_SECRET:            $(ParameterValidation.ARM_CLIENT_SECRET)
+              ARM_OBJECT_ID:                $(ParameterValidation.ARM_OBJECT_ID)
+              ARM_SUBSCRIPTION_ID:          $(ParameterValidation.ARM_SUBSCRIPTION_ID)
+              ARM_TENANT_ID:                $(ParameterValidation.ARM_TENANT_ID)
+              AZURE_DEVOPS_EXT_PAT:         $(System.AccessToken)
+              CONFIG_REPO_PATH:             ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
+              CONTROL_PLANE_NAME:           ${{ parameters.control_plane_name }}
+              SYSTEM_ACCESSTOKEN:           $(System.AccessToken)
+              SAP_AUTOMATION_REPO_PATH:     ${{ parameters.sap_automation_repo_path }}
+              USE_MSI:                      $(Use_MSI)
 
   - stage:                             Remove_SAP_workload_zone
     displayName:                       "Removing the SAP workload zone"
@@ -114,6 +154,43 @@ stages:
         steps:
           - template:                  templates\download.yaml
           - task:                      PostBuildCleanup@4
+          - bash: |
+              #!/bin/bash
+              # Exit immediately if a command exits with a non-zero status.
+              set -e
+              if ["${WL_ARM_SUBSCRIPTION_ID:0:2}" == '$(']; then
+                echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;isOutput=true]$WL_ARM_SUBSCRIPTION_ID"
+              else
+                echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;isOutput=true]"
+              fi
+              if ["${WL_ARM_CLIENT_ID:0:2}" == '$(']; then
+                echo "##vso[task.setvariable variable=ARM_CLIENT_ID;isOutput=true]$WL_ARM_CLIENT_ID"
+              else
+                echo "##vso[task.setvariable variable=ARM_CLIENT_ID;isOutput=true]"
+              fi
+              if ["${WL_ARM_CLIENT_SECRET:0:2}" == '$(']; then
+                echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;isOutput=true]$WL_ARM_CLIENT_SECRET"
+              else
+                echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;isOutput=true]"
+              fi
+              if ["${WL_ARM_TENANT_ID:0:2}" == '$(']; then
+                echo "##vso[task.setvariable variable=ARM_TENANT_ID;isOutput=true]$WL_ARM_TENANT_ID"
+              else
+                echo "##vso[task.setvariable variable=ARM_TENANT_ID;isOutput=true]"
+              fi
+              if ["${WL_ARM_OBJECT_ID:0:2}" == '$(']; then
+                echo "##vso[task.setvariable variable=ARM_OBJECT_ID;isOutput=true]$WL_ARM_OBJECT_ID"
+              else
+                echo "##vso[task.setvariable variable=ARM_OBJECT_ID;isOutput=true]"
+              fi
+            env:
+              WL_ARM_SUBSCRIPTION_ID:  $(ARM_SUBSCRIPTION_ID)
+              WL_ARM_CLIENT_ID:        $(ARM_CLIENT_ID),
+              WL_ARM_CLIENT_SECRET:    $(ARM_CLIENT_SECRET)
+              WL_ARM_TENANT_ID:        $(ARM_TENANT_ID)
+              WL_ARM_OBJECT_ID:        $(ARM_OBJECT_ID)
+            name:                      ParameterValidation
+            displayName:               Parameter Validation
           - task:                      Bash@3
             inputs:
               targetType:              'filePath'
